#!/bin/bash

common(){
  files=/srv/dotfiles
  mode=hidpi

  # i3
  cp $files/.config/i3/config-$mode ~/.config/i3/config

  # gtk
  cp $files/.gtkrc-2.0-$mode ~/.gtkrc-2.0
  cp $files/.config/gtk-3.0/settings-$mode.ini ~/.config/gtk-3.0/settings.ini
  
  # xresources
  cp $files/.Xresources-$mode ~/.Xresources

  # dunst
  cp $files/.config/dunst/dunstrc-$mode ~/.config/dunst/dunstrc
  
  # chromium
  cp $files/.config/chromium-flags-$mode.conf ~/.config/chromium-flags.conf
}

common >/dev/null 2>&1
