#!/bin/bash

common(){
  home=/home/gms
  files=/srv/dotfiles
  mode=hidpi

  # i3
  cp $files/.config/i3/config-$mode $home/.config/i3/config

  # gtk
  cp $files/.gtkrc-2.0-$mode $home/.gtkrc-2.0
  cp $files/.config/gtk-3.0/settings-$mode.ini $home/.config/gtk-3.0/settings.ini
  
  # xresources
  cp $files/.Xresources-$mode $home/.Xresources

  # dunst
  cp $files/.config/dunst/dunstrc-$mode $home/.config/dunst/dunstrc
  
  # chromium
  cp $files/.config/chromium-flags-$mode.conf $home/.config/chromium-flags.conf

  # change git repos to git://
  for repo in archlinux dotfiles salt; do
    (cd /srv/$repo;  git remote set-url origin git@github.com:lero/$repo.git)
  done
  (cd $home/bin; git remote set-url origin git@github.com:lero/shell.git)
}

common &>/dev/null
